version: '3.1'

services:

  wordpress:
    build: .
    image: wordpress
    restart: always
    env_file: ./.env
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  node-js:
    container_name: node-js
    image: node:16.14.2-stretch
    command: tail -f /dev/null
    working_dir: /themes
    volumes:
      - ./wordpress/wp-content/themes/:/themes

volumes:
  wordpress:
  db:
  themes: